spring:
  datasource:
    url: jdbc:mysql://mysql-db:3307/atenea-courses
    username: "root"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect