spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: "root"
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect